from tortoise.models import Model
from tortoise import fields


class AnaliseAtendimento(Model):

    id = fields.IntField(pk=True)
    data_inicio_analise = fields.DateField(null=True, description="Data do Início da Análise")
    matricula_funcionario = fields.CharField(max_length=100, null=True, description="Matrícula do Funcionário")
    nome_funcionario = fields.CharField(max_length=255, null=True, description="Nome Funcionário")
    data_realizacao = fields.DateField(null=True, description="Data da Realização")
    tipo_exame = fields.CharField(max_length=255, null=True, description="Tipo de Exame")
    exame = fields.CharField(max_length=255, null=True, description="Exame")
    unidade_funcionario = fields.CharField(max_length=255, null=True, description="Unidade do Funcionário")
    valor_pagar = fields.DecimalField(max_digits=10, decimal_places=2, null=True, description="Valor a Pagar")
    inconsistencia = fields.CharField(max_length=255, null=True, description="Inconsistência")
    status_atendimento = fields.CharField(max_length=100, null=True, description="Status do Atendimento")
    sequencial_ficha = fields.CharField(max_length=100, null=True, description="Sequencial Ficha")
    sequencial_resultado = fields.CharField(max_length=100, null=True, description="Sequencial Resultado")
    nome_responsavel_aso = fields.CharField(max_length=255, null=True, description="Nome do Resposável ASO")
    assinatura_digital_aso = fields.CharField(max_length=50, null=True, description="Assinatura Digital ASO")
    assinatura_digital_ficha_clinica = fields.CharField(max_length=50, null=True, description="Assinatura Digital Ficha Clínica")
    atendido_via_socnet = fields.CharField(max_length=50, null=True, description="Atendido via Socnet")
    cargo_funcionario = fields.CharField(max_length=255, null=True, description="Cargo do Funcionário")
    cidade_prestador = fields.CharField(max_length=255, null=True, description="Cidade do Prestador")
    classificacao_socged = fields.CharField(max_length=255, null=True, description="Classificação SOCGED")
    cliente_socnet = fields.CharField(max_length=255, null=True, description="Cliente SOCNET")
    cnpj_empresa = fields.CharField(max_length=20, null=True, description="CNPJ da Empresa")
    cnpj_cpf_prestador = fields.CharField(max_length=20, null=True, description="CNPJ/CPF do Prestador")
    cobranca_ficha_clinica = fields.CharField(max_length=100, null=True, description="Cobrança Ficha Clínica")
    codigo_empresa = fields.CharField(max_length=100, null=True, description="Código da Empresa")
    codigo_exame = fields.CharField(max_length=100, null=True, description="Código do Exame")
    codigo_exame_socnet = fields.CharField(max_length=100, null=True, description="Código do Exame mapeado SOCNET")
    codigo_funcionario = fields.CharField(max_length=100, null=True, description="Código do Funcionário")
    codigo_prestador = fields.CharField(max_length=100, null=True, description="Código do Prestador")
    codigo_ged_aso = fields.CharField(max_length=100, null=True, description="Código GED ASO")
    codigo_ged_consulta = fields.CharField(max_length=100, null=True, description="Código GED Consulta")
    codigo_ged_ficha = fields.CharField(max_length=100, null=True, description="Código GED Ficha")
    codigo_ged_resultado = fields.CharField(max_length=100, null=True, description="Código GED Resultado")
    conselho_classe_responsavel_aso = fields.CharField(max_length=100, null=True, description="Conselho de Classe do Responsável ASO")
    cpf_funcionario = fields.CharField(max_length=20, null=True, description="CPF do Funcionário")
    data_criacao_ficha = fields.DateField(null=True, description="Data Criação da Ficha")
    data_contagem = fields.DateField(null=True, description="Data da Contagem")
    data_ficha = fields.DateField(null=True, description="Data da Ficha")
    data_ultima_alteracao_resultado = fields.DateField(null=True, description="Data da Última Alteração do Resultado")
    data_emissao_documento_fiscal = fields.DateField(null=True, description="Data de Emissão do Documento Fiscal")
    data_liberacao = fields.DateField(null=True, description="Data de Liberação")
    data_postagem = fields.DateField(null=True, description="Data de Postagem")
    data_recebimento = fields.DateField(null=True, description="Data de Recebimento")
    data_upload_ged_aso = fields.DateField(null=True, description="Data do Upload GED ASO")
    data_upload_ged_consulta = fields.DateField(null=True, description="Data do Upload GED Consulta")
    data_upload_ged_ficha = fields.DateField(null=True, description="Data do Upload GED Ficha")
    data_upload_ged_resultado = fields.DateField(null=True, description="Data do Upload GED Resultado")
    data_emissao_aso = fields.DateField(null=True, description="Data Emissão do ASO")
    data_ultima_alteracao = fields.DateField(null=True, description="Data Última Alteração")
    empresa_funcionario = fields.CharField(max_length=255, null=True, description="Empresa do Funcionário")
    estado_prestador = fields.CharField(max_length=50, null=True, description="Estado do Prestador")
    matricula_rh_funcionario = fields.CharField(max_length=100, null=True, description="Matrícula RH do Funcionário")
    nome_banco = fields.CharField(max_length=255, null=True, description="Nome do Banco")
    nome_lote = fields.CharField(max_length=255, null=True, description="Nome do Lote")
    nome_prestador = fields.CharField(max_length=255, null=True, description="Nome do Prestador")
    numero_documento_fiscal = fields.CharField(max_length=100, null=True, description="Número do Documento Fiscal")
    prestador_socnet = fields.CharField(max_length=100, null=True, description="Prestador Socnet")
    setor_funcionario = fields.CharField(max_length=255, null=True, description="Setor do Funcionário")
    situacao_empresa = fields.CharField(max_length=100, null=True, description="Situação da Empresa")
    tipo_pagamento = fields.CharField(max_length=100, null=True, description="Tipo de Pagamento")
    tipo_pessoa = fields.CharField(max_length=50, null=True, description="Tipo Pessoa")
    uf_conselho_classe_responsavel_aso = fields.CharField(max_length=10, null=True, description="UF Conselho de Classe Responsável ASO")
    usuario_ultima_alteracao = fields.CharField(max_length=100, null=True, description="Usuário Última Alteração")
    valor_documento_fiscal = fields.DecimalField(max_digits=12, decimal_places=2, null=True, description="Valor do Documento Fiscal")
    created_at = fields.DatetimeField(auto_now_add=True, description="Data de criação do registro")

    class Meta:
        table = "task_analise_atendimento_cm"

class InconsistenciasAtendimento(Model):

    id = fields.IntField(pk=True)
    nome_funcionario = fields.CharField(max_length=255, null=True, description="Nome Funcionário")
    exame = fields.CharField(max_length=255, null=True, description="Exame")
    inconsistencia = fields.CharField(max_length=255, null=True, description="Inconsistência")
    observacao_cliente = fields.TextField(null=True, description="Observação do Cliente")
    status_inconsistencia = fields.CharField(max_length=100, null=True, description="Status da Inconsistência")
    codigo_exame = fields.CharField(max_length=100, null=True, description="Código do Exame")
    cpf_funcionario = fields.CharField(max_length=20, null=True, description="CPF do Funcionário")
    data_observacao_cliente = fields.DateField(null=True, description="Data da Observação do Cliente")
    data_observacao_prestador = fields.DateField(null=True, description="Data da Observação do Prestador")
    empresa_funcionario = fields.CharField(max_length=255, null=True, description="Empresa do Funcionário")
    hora_observacao_cliente = fields.CharField(max_length=8, null=True, description="Hora da Observação do Cliente")
    hora_observacao_prestador = fields.CharField(max_length=8, null=True, description="Hora da Observação do Prestador")
    observacao_prestador = fields.TextField(null=True, description="Observação do Prestador")
    created_at = fields.DatetimeField(auto_now_add=True, description="Data de criação do registro")

    class Meta:
        table = "task_inconsis_atendimento_cm"